server:
  port: 11000
spring:
  jpa:
    show-sql: true
    database-platform: "org.hibernate.dialect.H2Dialect"
  datasource:
    driver-class-name: "org.h2.Driver"
    platform: "postgres"
    username: "sa"
    password: "sa"
    url: "jdbc:h2:file:~/ed-dev"
  h2:
    console:
      enabled: true
