server:
  port: 11000
spring:
  jpa:
    show-sql: true
    database-platform: "org.hibernate.dialect.H2Dialect"
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "sa"
    url: "jdbc:h2:mem:ed-sample"
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
